name: ubuntu-llvm-build-fluir

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libtinyxml2-dev libfmt-dev

      - name: Configure CMake
        run: cmake --preset llvm-release
      - name: Build
        run: cmake --build --preset llvm-release
      - name: Run tests
        run: ctest --preset llvm-release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LLVM-Release
          path: |
            build/llvm-release/
            !build/llvm-release/**/*.o
            !build/llvm-release/**/*.obj
            !build/llvm-release/CMakeFiles/
          retention-days: 7
