name: ubuntu-build-fluir

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libtinyxml2-dev libfmt-dev
      - name: Configure GCC
        run: cmake --preset gcc-release
      - name: Build GCC
        run: cmake --build --preset gcc-release
      - name: Run tests GCC
        run: ctest --preset gcc-release --output-junit test_results.xml
        # LLVM is not published as an artifact, but is built for testing and
        # standards compliance verification
      - name: Configure LLVM
        run: cmake --preset llvm-release
      - name: Build LLVM
        run: cmake --build --preset llvm-release
      - name: Run tests LLVM
        run: ctest --preset llvm-release
      - name: Create tar archive
        run: |
          cd build
          tar -czf gcc-release.tar.gz \
            --exclude='gcc-release/**/*.o' \
            --exclude='gcc-release/**/*.obj' \
            --exclude='gcc-release/CMakeFiles/' \
            gcc-release/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Compiler-VM-Release
          path: build/gcc-release.tar.gz
          retention-days: 7

  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      - name: Create Venv
        run: |
          python -m venv .venv
        working-directory: editor/server
      - name: Setup Venv
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[build]
        working-directory: editor/server
      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest --junitxml test_results.xml
        working-directory: editor/server
      - name: Build executable
        run: |
          source .venv/bin/activate
          python build.py
        working-directory: editor/server
      - name: Create tar archive
        run: |
          cd editor/server
          tar -czf editor-be.tar.gz \
          dist/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Editor-BE
          path: |
            editor/server/editor-be.tar.gz
          retention-days: 7

  build-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
        working-directory: editor/client
      - name: Build Electron App
        run: npm run dist
        working-directory: editor/client
      - name: Create tar archive preserving permissions
        run: |
          cd editor/client
          tar -czf editor-fe.tar.gz \
            release/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Editor-FE
          path: |
            editor/client/editor-fe.tar.gz
          retention-days: 7

  build-launcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      - name: Create Venv
        run: |
          python -m venv .venv
        working-directory: launcher
      - name: Setup Venv
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[build]
        working-directory: launcher
      - name: Build executable
        run: |
          source .venv/bin/activate
          python build.py
        working-directory: launcher
      - name: Create tar archive
        run: |
          cd launcher
          tar -czf launcher.tar.gz \
          dist/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Launcher
          path: |
            launcher/launcher.tar.gz
          retention-days: 7
  
  build-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: artifacts
      - name: debug
        run: |
          cd artifacts
          pwd
          ls
      

