name: windows-msvc-build-fluir

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          vcpkg install tinyxml2 fmt gtest --triplet x64-windows
      - name: Setup Developer Command Prompt and Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --preset msvc-release
          cmake --build --preset msvc-release
          ctest --preset msvc-release
        shell: cmd
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MSVC-Release
          path: |
            build/msvc-release/
            !build/msvc-release/**/*.o
            !build/msvc-release/**/*.obj
            !build/msvc-release/CMakeFiles/
          retention-days: 7
  build-python:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      - name: Create Venv
        run: |
          python -m venv .venv
        working-directory: editor/server
      - name: Setup Venv
        run: |
          .venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -e .[build]
        working-directory: editor/server
      - name: Run Tests
        run: |
          .venv/Scripts/activate
          pytest --junitxml test_results.xml
        working-directory: editor/server
      - name: Build executable
        run: |
          .venv/Scripts/activate
          python build.py
        working-directory: editor/server
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Editor-BE
          path: |
            editor/server/dist/
          retention-days: 7
  build-electron:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
        working-directory: editor/client
      - name: Build Electron App
        run: npm run dist
        working-directory: editor/client
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Editor-FE
          path: |
            editor/client/release/
          retention-days: 7
  build-launcher:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      - name: Create Venv
        run: |
          python -m venv .venv
        working-directory: launcher
      - name: Setup Venv
        run: |
          .venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -e .[build]
        working-directory: launcher
      - name: Build executable
        run: |
          .venv/Scripts/activate
          python build.py
        working-directory: launcher
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Launcher
          path: |
            launcher/dist/
          retention-days: 7

