name: windows-msvc-build-fluir

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          vcpkg install tinyxml2 fmt
      - name: Configure CMake
        run: cmake --preset msvc-release
      - name: Build
        run: cmake --build --preset msvc-release
      - name: Run tests
        run: ctest --preset msvc-release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MSVC-Release
          path: |
            build/msvc-release/
            !build/msvc-release/**/*.o
            !build/msvc-release/**/*.obj
            !build/msvc-release/CMakeFiles/
          retention-days: 7
